### ISSUE TITLE
web!!!

### ISSUE THREAD

**Issue by MMAKENPO** [PabloRosas17/Tuner#1]
hola hermano....muchas felicidades pero por favor cual es el link para tu projecto?ayudame por favor

**Comment by PabloRosas17** [comment]
hola hermano, este proyecto lo inventé yo mismo.
que me estas pidiendo, ¿con qué necesitas ayuda?

**Comment by MMAKENPO** [comment]
hermano saludos desde Grecia!!!espero que estas muy bien!hermano es para buscamos canciones y albums de itunes...si???
